"""Added location columns

Revision ID: 99b8c2cc8dfc
Revises: 6c59ef4bcf7f
Create Date: 2022-04-27 14:14:46.880841

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import geoalchemy2

# revision identifiers, used by Alembic.
revision = '99b8c2cc8dfc'
down_revision = '6c59ef4bcf7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('restaurant_location', geoalchemy2.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'), nullable=True))
    op.add_column('user_address', sa.Column('user_location', geoalchemy2.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_address_user_location', table_name='user_address', postgresql_using='gist', postgresql_ops={})
    op.drop_column('user_address', 'user_location')
    op.drop_index('idx_restaurants_restaurant_location', table_name='restaurants', postgresql_using='gist', postgresql_ops={})
    op.drop_column('restaurants', 'restaurant_location')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###
